In [23]:
import numpy as np

In [26]:
a = np.array([1,2,3,4])
b = np.array([2,3,4,5])

In [27]:
a*b

array([ 2,  6, 12, 20])

In [28]:
a = np.array([1,2,3,4,5])
type(a)

In [30]:
b = np.array([3.14,4,3,8])

array([3.14, 4.  , 3.  , 8.  ])

# sifirdan array olusturma

In [37]:
 np.zeros(10, dtype=int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [38]:
np.ones((3,5),dtype=int)

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [40]:
np.full((4,5),)

array([[3, 3, 3, 3, 3],
       [3, 3, 3, 3, 3],
       [3, 3, 3, 3, 3],
       [3, 3, 3, 3, 3]])

In [41]:
np.arange(0,31,3)

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27, 30])

In [42]:
np.linspace(0,1,10)

array([0.        , 0.11111111, 0.22222222, 0.33333333, 0.44444444,
       0.55555556, 0.66666667, 0.77777778, 0.88888889, 1.        ])

In [46]:
np.random.normal(10,4,(3,4)) 

array([[ 5.91611235,  9.33998852,  4.9096995 ,  9.52738148],
       [14.11786444, 16.6796949 ,  9.97904111,  4.42281923],
       [ 7.70905476, 17.32803367,  2.35762642,  3.03435526]])

In [49]:
np.random.randint(0,10,(3,3))

array([[2, 4, 8],
       [8, 6, 9],
       [7, 2, 8]])