In [14]:
import numpy as np

# reshape (sekillendirme)

In [15]:
np.arange(1,10)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [16]:
np.arange(1,10).reshape((3,3))

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [17]:
a = np.arange(1,10)

In [18]:
a

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [19]:
a.ndim   # vektör = 1 boyutlu array 
        # matrix = 2 boyutlu array

1

In [22]:
b = a.reshape((1,9))

In [23]:
b.ndim

2

# aray birlestirme (concatenation)

In [24]:
x = np.array([1,2,3])
y = np.array([4,5,6])

In [25]:
np.concatenate([x,y])

array([1, 2, 3, 4, 5, 6])

In [26]:
z = np.array([7,8,9])

In [27]:
np.concatenate([x,y,z])


array([1, 2, 3, 4, 5, 6, 7, 8, 9])

IKI BOYUT ICIN

In [28]:
a = np.array([[1,2,3],
             [4,5,6]])

In [29]:
np.concatenate([a,a])

array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3],
       [4, 5, 6]])

axis eksen belirtir
0 = satirlari / 1 = sütunları ifade eder

In [30]:
np.concatenate([a,a],axis=1)


array([[1, 2, 3, 1, 2, 3],
       [4, 5, 6, 4, 5, 6]])

# array ayırma (splitting)

In [31]:
y = np.array([1,2,3,99,99,3,2,1])

In [34]:
np.split(y,[3,5])

[array([1, 2, 3]), array([99, 99]), array([3, 2, 1])]

In [35]:
a, b, c = np.split(y,[3,5])

2 boyutlu array ayırma

In [37]:
m = np.arange(16).reshape(4,4)
m

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [38]:
np.vsplit(m,[2]) # 2.satirdan boler

[array([[0, 1, 2, 3],
        [4, 5, 6, 7]]),
 array([[ 8,  9, 10, 11],
        [12, 13, 14, 15]])]

In [42]:
sol, sag = np.hsplit(m, [2]) # 2. sütundan boler
sol

array([[ 0,  1],
       [ 4,  5],
       [ 8,  9],
       [12, 13]])

# sıralama (sorting)

In [43]:
v = np.array([2,1,4,3,5])

In [44]:
v

array([2, 1, 4, 3, 5])

In [45]:
np.sort(v)

array([1, 2, 3, 4, 5])

2 BOYUTLU ARRAY SIRALAMA

In [48]:
n = np.random.normal(20,5,(3,3))
n

array([[27.92640525, 18.81694435, 17.76182561],
       [22.77173274, 16.91610375, 13.00016743],
       [29.61744333, 11.46621404, 14.17784439]])

In [49]:
np.sort(n,axis=1) # satırları kendi icinde sıralar

array([[17.76182561, 18.81694435, 27.92640525],
       [13.00016743, 16.91610375, 22.77173274],
       [11.46621404, 14.17784439, 29.61744333]])

In [50]:
np.sort(n,axis=0) # sutunları kendi icinde sıralar

array([[22.77173274, 11.46621404, 13.00016743],
       [27.92640525, 16.91610375, 14.17784439],
       [29.61744333, 18.81694435, 17.76182561]])