In [1]:
import numpy as np

Index ile elemanlara erismek

In [6]:
a = np.random.randint(10, size = 10)
a

array([3, 8, 9, 6, 4, 3, 0, 3, 2, 5])

In [7]:
a[3]

6

In [16]:
m = np.random.randint(10, size = (3,5) )
m

array([[4, 5, 0, 2, 3],
       [9, 6, 5, 5, 2],
       [5, 2, 4, 3, 0]])

In [17]:
m[2,4]=99
m

array([[ 4,  5,  0,  2,  3],
       [ 9,  6,  5,  5,  2],
       [ 5,  2,  4,  3, 99]])

In [20]:
m[1,4]=2.7
m
 #numpy fix type kullanır (C dili gibi tek bir veri tipi)

array([[ 4,  5,  0,  2,  3],
       [ 9,  6,  5,  5,  2],
       [ 5,  2,  4,  3, 99]])

Slicing Ile Elemanlara Erismek (Array Alt Kumesine Erismek)

In [21]:
a = np.arange(20,30)
a

array([20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [23]:
a[0:3] #   [0,3) olarak alır

array([20, 21, 22])

In [24]:
a[:3]

array([20, 21, 22])

In [26]:
a[3:] #3 ten sona kadar git

array([23, 24, 25, 26, 27, 28, 29])

In [27]:
a[1::2] #ilk indexten 2 şer atlayarak gider

array([21, 23, 25, 27, 29])

In [28]:
# IKI BOYUTLU SLICE ISLEMLERİ

In [31]:
n = np.random.randint(10,size=(5,5))
n

array([[8, 8, 8, 0, 4],
       [7, 0, 0, 9, 1],
       [0, 3, 7, 7, 9],
       [3, 2, 6, 1, 6],
       [2, 4, 3, 5, 1]])

In [32]:
n[:,0] # tum satırlası seç , ilk sütun

array([8, 7, 0, 3, 2])

In [33]:
n[3,:] # 4. satır , tüm sütunlar

array([3, 2, 6, 1, 6])

In [35]:
n[0:2,0:3] # 0-2 arası satirlar, 0-3 arasi sütunlar

array([[8, 8, 8],
       [7, 0, 0]])

In [36]:
n[:,:2] # tüm satirlar ve ilk iki sütun

array([[8, 8],
       [7, 0],
       [0, 3],
       [3, 2],
       [2, 4]])

# alt kume uzerinde islem yapmak

In [37]:
a = np.random.randint(10,size=(5,5))
a

array([[6, 7, 5, 5, 7],
       [7, 2, 2, 2, 3],
       [2, 0, 0, 9, 9],
       [5, 3, 6, 7, 6],
       [5, 9, 9, 1, 5]])

In [38]:
alt_a = a[0:3,0:2]
alt_a

array([[6, 7],
       [7, 2],
       [2, 0]])

In [40]:
alt_a[0,0] = 9999
alt_a[1,1] = 8888
alt_a

array([[9999,    7],
       [   7, 8888],
       [   2,    0]])

In [41]:
a

array([[9999,    7,    5,    5,    7],
       [   7, 8888,    2,    2,    3],
       [   2,    0,    0,    9,    9],
       [   5,    3,    6,    7,    6],
       [   5,    9,    9,    1,    5]])

In [42]:
m = np.random.randint(10,size=(5,5))
m

array([[9, 5, 6, 3, 4],
       [6, 5, 9, 5, 9],
       [4, 3, 7, 1, 2],
       [6, 2, 5, 0, 9],
       [0, 7, 3, 7, 1]])

In [43]:
alt_b = m[0:3,0:2].copy() # ana arrayden bagımsızlastırır

In [46]:
alt_b[0,0]=9874
alt_b*3

array([[29622,    15],
       [   18,    15],
       [   12,     9]])

In [45]:
m


array([[9, 5, 6, 3, 4],
       [6, 5, 9, 5, 9],
       [4, 3, 7, 1, 2],
       [6, 2, 5, 0, 9],
       [0, 7, 3, 7, 1]])