## FANCY INDEX ile elemanlara erismek

fancy = fantastik büyüleyici anlamına gelmekte çok kullanacagımız bir index

In [2]:
import numpy as np 
v = np.arange(0,30,3)
v

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27])

In [3]:
al_getir=[1,3,5]

In [4]:
v[al_getir]

array([ 3,  9, 15])

In [6]:
m =  np.arange(9).reshape((3,3))
m

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [8]:
satir = np.array([0,1])
sutun = np.array([1,2])
m[satir,sutun]

array([1, 5])

basit index ile fancy index

In [9]:
m[0,[1,2]]

array([1, 2])

In [10]:
#slice

In [11]:
m[0:,[1,2]]

array([[1, 2],
       [4, 5],
       [7, 8]])